---
repos:
  - repo: local
    hooks:
      - id: kubeconform
        name: Validate Kubernetes manifests
        entry: task kubernetes:kubeconform
        language: system
        pass_filenames: false
        types: [yaml]
        files: ^kubernetes/.*\.(yaml|yml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
