---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      strategy: RollingUpdate

    env:
      - name: HAJIMARI_DEFAULT_GROUP
        value: "default"

    persistence:
      config:
        enabled: true
        existingClaim: hajimari-config  # Reference your existing PVC

    # persistence:
    #   config:
    #     enabled: true
    #     storageClass: configs-nfs
    #     accessMode: ReadWriteOnce
    #     size: 1Gi
    #     volumeAttributes:
    #       server: ${NAS_IP}
    #       share: ${SETTINGS_NAS_APPDATA_PATH}

    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - networking
      name: "fabrice"
      # customApps:
      #   - name: Some External Cluster Service
      #     url: http://192.168.1.100:5000
      #     icon: test-tube
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Drive
              url: "https://drive.google.com"
            - name: AWS
              url: "https://us-east-1.console.aws.amazon.com"
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
            - name: Twitch
              url: "https://twitch.tv"
        - name: Reading
          links:
            - name: Dev.to
              url: "https://dev.to"
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"

    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:

          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"

          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Alternative to Homepage
          gethomepage.dev/group: Operations
          gethomepage.dev/icon: hajimari.png
          gethomepage.dev/name: Toboshii

        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
