---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    #env:
      #- name: HAJIMARI_DEFAULT_GROUP
        #value: "default"

    persistence:
      config:
        enabled: true
        existingClaim: hajimari-config  # Reference your existing PVC

    # persistence:
    #   config:
    #     enabled: true
    #     storageClass: configs-nfs
    #     accessMode: ReadWriteOnce
    #     size: 1Gi
    #     volumeAttributes:
    #       server: ${NAS_IP}
    #       share: ${SETTINGS_NAS_APPDATA_PATH}

    hajimari:
      name: "Fabrice"
      title: Apps

      alwaysTargetBlank: true

      showAppUrls: false
      showBookmarkGroups: true
      showGlobalBookmarks: true
      defaultSearchProvider: Google

      searchProviders:
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com

      defaultEnable: true

      customApps:
        - group: server
          apps:
            - name: PVE-Cluster
              url: 'https://10.0.40.10:8006'
              icon: 'mdi:server'
              info: 'This is the Proxmox Cluster'
        - group: network
          apps:
            - name: unifi-controlller
              icon: mdi:router-network
              url: "https://unifi.ui.com/consoles/D8B37045EAC900000000077FBBDD0000000007DC745C00000000645EEBC7:1521887693/network/default/dashboard"

      globalBookmarks:
        - group: Kubernetes
          bookmarks:
            - name: fabricesemti80/home-cluster-2024
              url: 'https://github.com/fabricesemti80/home-cluster-2024'
            - name: k8s-at-home-search
              url: 'https://whazor.github.io/k8s-at-home-search'
        - group: Communication
          bookmarks:
            - name: Discord
              url: 'https://discord.com'
            - name: Gmail
              url: 'https://gmail.com'
        - group: Development
          bookmarks:
            - name: Dev
              url: 'https://dev.to'
            - name: Medium
              url: 'https://medium.com'

      namespaceSelector:
        matchNames:
          - default

    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:

          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"

          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Alternative to Homepage
          gethomepage.dev/group: Operations
          gethomepage.dev/icon: hajimari.png
          gethomepage.dev/name: Toboshii

        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
