apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hnnyYveD4HaJI5923RMkR9QY1SufmIZ8HPXOzOeHVsgosoWy,iv:I63jenosi2S5gfqqcv3qa50iNnYwu2K5wKzanorq07s=,tag:YF89NqqlpN2rg1dghug8Dg==,type:str]
    credentials.json: ENC[AES256_GCM,data:n5AkvwoC8D6KnablcFPaVlW7NN+ztBYI3Ng6xMLEHzjHaXZHeI4mO9gnQ8UrOLgAhGnAOzvFAATnTQuisXzvc+mh6wvZUqbmvgfQCGNvngx3vvAnCA7zEbx/u1hYGrUvH0uSAVjvuPLpLwNEk8Ugl991qSa3EnFZXsQ/LEqAY1Qh1Bjc5qdUz3rjIZ42nXxAhvUFoWa5Z/Ni+dWiDTC1AHwRIg9l4UNaJs/eJcDoeg==,iv:ZU9viShstmXcvz3FHk+A9txzQ6I1hQUhq/vvwc453Zw=,tag:IPlXE1b72Zi4p7Fp5mkeyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17d79xwwv043mkvf45yfr372hc520nd468jxtm0a7wap4an3nxscsn8qtm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N1ZJUmJ4Z1pROHlSQUZK
            cWNDRVFKM1E0eVNuZEFxd1plUGtZMitreEVrCnQ1UXovc1FpajdPYkkvSHIrMlV6
            TWhUV01TaCtZUGtmcU5QL2RpSHoyeGMKLS0tIE9oVWZPeE1jRTlNY05takJNZEh2
            azNlM2s2QzZ6Vi9oaFlJdU14cmhZdEkKSm5osgKQ7V4R5UbabOBmG9ZySwj6BRxr
            IHKywUUb1Pyf2jU45QjbZcPVyoVD3uJwpMDMJsvgnKHiE+aErOFnRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T20:42:13Z"
    mac: ENC[AES256_GCM,data:B9lpTJH/2/4EX0GKMX4hl5djwYgqgNlLeNWsvnfQaW6GpSZmabDnVqnNYKqASqI5X3nNMedRn+pBjFgOojMi7ihV4paDemuwq/gbgp9iT/jkVpODwd7nlo9HBVUzLJDdR4GHFuQEItq3inUtWCbmdMSL62sYVHugup8nhS9VjPQ=,iv:Rj5zzhHTeWWWzOKB4AFXSHbMv9hiaj4KMYD2g5/rIGY=,tag:RGpMeJml+lksI8eoCSMXSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
