apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZAwY2QH2TzVz/Ka5WgaPkmKSjNUq04avVBD/6LxOo6LPOFH4,iv:u3r/+HfkXl+ocEophzSMb5ik0pFvxGO4gUuZeMcCKTM=,tag:Bon857v2YhEwDp1YTOV4iQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Z5IeALIDcixLmUwtXkA7hEkaO8nU8MhCkSdckjCYAIcDN7iXV+l2x5QDVWhkoM2EDQKDnXt4myTKirlfpRi409DcKud5HMfxJ1vIv1/92hHeXXdn4/VONxRXSRdgwjNIwGaWVghm9XJD6EnLdZIuwkGer9mL3xla/MLuu/0TnL06KkYRT+Reo6vqMBkjKCcDsb+H1EcPXvnAstX9a/gsUPdtXRn2aoh9md+wJZOaaA==,iv:YqPnM4qcKlG0o/51ACO/4sqvUyEu3sGmR39o+csWwYs=,tag:mJyofWTU0Ne9IpfRrFZhAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17d79xwwv043mkvf45yfr372hc520nd468jxtm0a7wap4an3nxscsn8qtm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeFJ2ODB0WS9TRklVY25h
            Qm1ZZU9lKzVqUE5HTWRFQVFQMXYzQWJNV1NFCmU2bVZ5QzdMZnBvWTRWY011cThQ
            NitDWWQ5emg3WUdUQWtEd212RjR6VlEKLS0tIEFnVmswSHlRNUo3dXd5Mzh4NGpX
            TE9GVmxtdFZyYzhRYkVuT3JoSFhPOE0Kq1fEpJDtvPV7BWjWr8evAhPARZ0A3Yql
            qaSLPimGXqV+ySzvl9eP793/azNIgg3wwfKaoSgSVE/g+KGYrVVP7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T20:00:46Z"
    mac: ENC[AES256_GCM,data:ElDfp1si0EZrAPDKDFkLYL9KPvJmClz3uXwHcYXhNmbrsKXFULO52dXXcXV1oovKWCb+fNAGmXTQJ2zk5tLi7eVzhferikOlDNxAwiSt3LTz3v9ehx/mV5Pchlxl7+yTX6msSks9V1ffvc9drnZrb4cZrADljBupmzqbS3dwX6o=,iv:Cr2NUO2fVY8wvursNqSnZxeIs5zv1Ei9kMqEOw8POr8=,tag:IGpKIA9V25XjBErBDqYSOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
