apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:pzC+fRqadMMs06RQHgx3TzeBCPZXyqERaN59VppzJILCqp7meiAZUw==,iv:NkhwG5qxuHcskekHZ7QLJCb1kYmVDE0GRtw6QFQYBmw=,tag:lbKfVVCiDupC/OB/8vyG6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17d79xwwv043mkvf45yfr372hc520nd468jxtm0a7wap4an3nxscsn8qtm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bWRJdUowaWs4Y2xTWnRL
            WW1JNEE0c0tkTGRicDZzenRIRXRHOWpFOUJJCkdvRmxZTFlPejVwdWFiVHU4YS92
            Vjg2OGZUd2VqbUFVdHJZUHZoanBJbkUKLS0tIFBvK0ZkQk9UeGRLd0x4UnNvV1V3
            ZnJEcmFSd053UE9wbTgxWkY5N3d2R1UKigj3LYjAFvAkNVTka58oQ2H9E6e3Lpmq
            UJARQFx9peccH+i9EcF0CyMr9gI+fOgFK5mLiRVBMGHr56rSQTc9wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T20:42:13Z"
    mac: ENC[AES256_GCM,data:aLOR2YijCEMZ9gCPRCm4ojbuIEylR6VoRpsLil5u53bW8+I6fyjqHCQyKPcninC54XqJn7Vn71PLns8QGqBu4jdRhWe+aVIuCdjQ5b0dIZxiI3+CXyc8PsaXwguXs8uBkEiEtdRq/IwkX3wb/xvtJaOmV1TJFmltPTOMi/cuy/s=,iv:f3+JK/qGH/zdsMadnS8yqBXRWw3NveydANRzosZHz7g=,tag:PDNOM4TAyCWJRRSjzI+Tkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
