apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:oHUeqLlKYNPKBAJRdPfOHls0qFpsJfJcKJEV5MpL/kCocWKP9UdlCA==,iv:W4O9DX9YToi+vbjLbyM0cMQz0cmmQ/DJNaYca4lCT5Q=,tag:swEymk8UHhXNiMm3sK7GKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17d79xwwv043mkvf45yfr372hc520nd468jxtm0a7wap4an3nxscsn8qtm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0duQVR6Z1UvUFo5VWN1
            QUwwSEsvTCtQeFFVRUlFZGlKRzhmSWloQ1JFCk04R2FoNUN4Q1FjNi9pN0psTmh3
            UlEyN3V1Vlc0bVlqVnhESklsY2FCSzQKLS0tIDlxaXBoeGRMTEtYMitxOUkrdTZH
            eTIrSE9nb2hBK1p6MkZEaWU3UDUzaGsKoajdXevlahqNUzHTOZ0897uI++dj88UR
            M3s5+Rg9GEPtEcEjPFu4Ly6CCC/uIDTzxS57DKlRlDMt/AqMHSaC8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T20:46:35Z"
    mac: ENC[AES256_GCM,data:NNzdW+E2FMVrLRE7iXqzEgnfe6xCWoQSjl6cDfDpi1zA9ERPgb5zN2D6VhPwNC0R5SkZw6qCkddgzpyDVo5JL2y7l8VAtQ8s/6jULAy5Pr8YXDk2IJG7eJXoXNfCAgx4yVCZs6qQr2msfrvOaSkNW77HTi9GeP3qrWOrKjmixTo=,iv:WD2E46Wi3jd/FsUtQW7HMY4ewsgNQLMHJPBrVH6WZYU=,tag:PA7rsmpWiAXrWlfT5/IUCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
