
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nzbhydra2:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${NAS_USER_ID}
            runAsGroup:  ${NAS_GROUP_ID}
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: linuxserver/nzbhydra2
              tag: 7.11.3
              pullPolicy: IfNotPresent
            env:
              NZBHYDRA2_PORT: &port 5076
              TZ: ${TIMEZONE}
              PUID: ${NAS_USER_ID}
              PGID: ${NAS_GROUP_ID}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      app:
        controller: nzbhydra2
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:download
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
          nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        hosts:
          - host: &host "nzbhydra2.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]

    persistence:
      config:
        enabled: true
        existingClaim: nzbhydra2-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      downloads:
        type: nfs
        server: 10.0.40.240
        path: /downloads
        globalMounts:
          - path: /downloads
      media:
        type: nfs
        server: 10.0.40.240
        path: /media
        globalMounts:
          - path: /media
