---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.4.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  values:
    controller:
      replicas: 1
