version: '3'

env:
  EDITOR: nvim

tasks:
  edit-sops-k8s:
    desc: Edit cluster secrets using SOPS with Neovim
    cmds:
      - EDITOR=nvim sops {{.KUBERNETES_DIR}}/flux/vars/cluster-secrets.sops.yaml

  view-sops-k8s:
    desc: View decrypted cluster secrets file
    cmds:
      - sops -d {{.KUBERNETES_DIR}}/flux/vars/cluster-secrets.sops.yaml

  edit-sops-cf:
    desc: Edit Cloudflare using SOPS with Neovim
    cmds:
      - EDITOR=nvim sops {{.KUBERNETES_DIR}}/apps/network/cloudflared/app/secret.sops.yaml

  view-sops-cf:
    desc: View decrypted Cloudflare secrets file
    cmds:
      - sops -d {{.KUBERNETES_DIR}}/apps/network/cloudflared/app/secret.sops.yaml

  view-k8s:
    desc: View current cluster secrets in Kubernetes
    cmds:
      - kubectl get secret cluster-secrets -n flux-system -o yaml

  view-k8s-decoded:
    desc: View decoded cluster secrets in Kubernetes
    cmds:
      - kubectl get secret cluster-secrets -n flux-system -o yaml | yq '.data | map_values(@base64d)'
