---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SETTING_EXAMPLE: Global settings for your cluster go in this file, this file is NOT encrypted
  SETTINGS_NAS_IP: 10.0.40.240
  SETTINGS_NAS_CONFIG_PATH: /data/config
  # SETTINGS_NAS_DATA_PATH: /k8s-data
  TIMEZONE: Europe/London
