---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: config-nfs
  resources:
    requests:
      storage: 1Gi

