apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UqYwkZBOc3fN+V3gTe4x86yITReI+0XJZgaoFOmz1z6NmZZuhfdrKw==,iv:B8z/TzIvKS/VnXz8+czfGbZnEXG4VrQNZfRRIgL0ekQ=,tag:OI0q9dFzRH7S/hwhhmPCPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17d79xwwv043mkvf45yfr372hc520nd468jxtm0a7wap4an3nxscsn8qtm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMzkzdzdkNm1GczI2WFN3
            eG1CZ3VTZWxBdmFib2tPWkxta3lnR0tPMVFFCkF0TnF0YVJOczlyNEg5VXFZdlBY
            eUowMzRTSXlEd25pblpLMDFyNWI0M2cKLS0tIHFCVVJqM0FGQjA0YWZ5V2drVTdC
            YjVsVjdObDN1eDVXZnlmZW5OallDNVEKz86Cc/8jIatz2Umw/PnK2X/JuISbaaef
            3FkZvtUT7BkbsQDKXZWA8rYVZnZiVSNjSHdOL9DNN2rxYcH1NIsZ2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T20:42:13Z"
    mac: ENC[AES256_GCM,data:nd6/A0LLKwJWER/wwJ9hVnv1JmNmx5MccnG8SUuPnXU8rKc0Hu/heq1MwNEPxBHXpwHmwAUNaR+W7/JmZQ/5yZuUdtXnFatikwA4w8c+2BMvIQ1ztIYYPTuL6e/WZc1DVJZechI8PdzNmPZNceyUKYNtGfq06jVQLM2OYgLyF98=,iv:mKfLmBubcf3+cInBERSnVkRKvkGh0QV0AX3uS7j5qnk=,tag:IblDbAIDDjDlD4fyvrzqXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
